export const blogData = [
  {
    id: 1,
    image: 'https://images.pexels.com/photos/9800036/pexels-photo-9800036.jpeg',
    title: 'Understanding Solar Panel Efficiency',
    description: 'Explore how solar panels convert sunlight into electricity and what affects their efficiency.',
    category: 'Solar Panels',
    date: 'September 10, 2025',
  },
  {
    id: 2,
    image: 'https://images.pexels.com/photos/9875420/pexels-photo-9875420.jpeg',
    title: 'Designing Eco-Friendly Solar Homes',
    description: 'Learn how to integrate solar technology into modern home design for maximum sustainability.',
    category: 'Design',
    date: 'September 9, 2025',
  },
  {
    id: 3,
    image: 'https://images.pexels.com/photos/8853507/pexels-photo-8853507.jpeg',
    title: 'New Innovations in Solar Technology 2025',
    description: 'Stay ahead with the latest advancements in solar energy tech and what they mean for the future.',
    category: 'Technology',
    date: 'September 7, 2025',
  },
  {
    id: 4,
    image: 'https://images.pexels.com/photos/9875444/pexels-photo-9875444.jpeg',
    title: 'Building Scalable Solar Energy Systems',
    description: 'Best practices for designing and deploying scalable solar power solutions.',
    category: 'Engineering',
    date: 'September 5, 2025',
  },
  {
    id: 5,
    image: 'https://images.pexels.com/photos/7527879/pexels-photo-7527879.jpeg',
    title: 'Solar Panel Placement: Roof vs Ground',
    description: 'Understand the pros and cons of different solar panel installation strategies.',
    category: 'Installation',
    date: 'September 3, 2025',
  },
  {
    id: 6,
    image: 'https://images.pexels.com/photos/9875423/pexels-photo-9875423.jpeg',
    title: 'Battery Storage vs Grid-Tied Systems',
    description: 'Compare solar energy storage options and when to choose off-grid or hybrid setups.',
    category: 'Energy Storage',
    date: 'September 1, 2025',
  },
  {
    id: 7,
    image: 'https://images.pexels.com/photos/7605826/pexels-photo-7605826.jpeg',
    title: 'Solar Incentives and Tax Credits Explained',
    description: 'Learn about financial incentives for switching to solar energy in 2025.',
    category: 'Finance',
    date: 'August 30, 2025',
  },
  {
    id: 8,
    image: 'https://images.pexels.com/photos/4254157/pexels-photo-4254157.jpeg',
    title: 'Troubleshooting Common Solar Issues',
    description: 'Identify and fix common problems in residential solar energy systems.',
    category: 'Maintenance',
    date: 'August 28, 2025',
  },
  {
    id: 9,
    image: 'https://images.pexels.com/photos/13205474/pexels-photo-13205474.jpeg',
    title: 'Maximizing Solar Energy Output',
    description: 'Tips and tricks to improve solar panel performance and efficiency.',
    category: 'Performance',
    date: 'August 26, 2025',
  },
  {
    id: 10,
    image: 'https://images.unsplash.com/photo-1554384645-13eab165c24b?auto=format&fit=crop&w=800&q=80',
    title: 'Getting Started with Solar for Beginners',
    description: 'A simple guide to understanding solar power and how to start using it at home.',
    category: 'Beginner',
    date: 'August 24, 2025',
  },
];
